// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izaxpvngminplyvtbuny.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6YXhwdm5nbWlucGx5dnRidW55Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDY0MDYsImV4cCI6MjA2NTU4MjQwNn0.XFEzcZ3IZZM_PUejhMdbKh28LnvUpbPt73auvTKIsLc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);